## Code for merging csv files from each month of the year into one 
## Please make sure the files are in the /place_visit_month/20xx folder that in the same directory with this code, change the year of the folder accordingly if you want to test these code
```{r}
# Load required libraries
library(dplyr)
library(readr)

# Set the directory containing the CSV files
# Change the FD01-2019 accordingly based on the user and the year
# Special case for 2019, use FD01-2019 and FD02-2019 for each user. For all the other years, change FD0x-2019 to 20xxTotal
path <- "place_visit_month/2019/FD01-2019"  

# Get a list of CSV files with the specified naming pattern
csv_files <- list.files(path = path, pattern = "2019-\\d{2}\\.csv$", full.names = TRUE)

# Read and combine all available CSV files
merged_data <- bind_rows(lapply(csv_files, read_csv))

# Save the merged data to a new CSV file
write_csv(merged_data, "FD-01-2019_place_visit.csv")

cat("Available files have been successfully merged.\n")
```
## Code for combining FD01/02's csv file seperatly. The result from privous merge steps are already stored in /FD0x/place_visit_data/
```{r}
# Set the path where your CSV files are stored
# change the FD02 to FD01 accordingly
file_path <- "FD02/place_visit_data/" 

# List all CSV files in the directory
csv_files <- list.files(path = file_path, pattern = "_place_visit.csv$", full.names = TRUE)

# Read and combine all CSV files into a single data frame
combined_data <- do.call(rbind, lapply(csv_files, read.csv))

# Save the combined data to a new CSV
write.csv(combined_data, file = file.path(file_path, "FD02_place_visit.csv"), row.names = FALSE)
```
